### PR TITLE
Barcode Support

### PR DESCRIPTION
**Pull request by gnanakeethan**
Please verify the code structure is correct. can you suggest a proper method to concat strings?

### CODE REVIEW

**Comment by gnanakeethan** [comment]
@kenshaw  This code doesnt support custom height. Uses default 200 dot height. Need to add that code. 
>> GS.h.<dots>

**Comment by kenshaw** [comment]
You can do string concatenation using the `+` operator, or `use fmt.Sprintf()`.

**Comment by gnanakeethan** [comment]
Can you verify my coding is right? This code works fine for me. 

This has added support for CODE128 as well. format (73) prints CODE128.

**Comment by kenshaw** [comment]
You don't need the calls to `e.reset()` in there. That just resets the default settings. It's used only because the `Feed` func resets the state of the printer, which is not the same as the default "zero values" for the corresponding Go variables (ie, width, height, etc). Not sure if the specification for the actual printers means that after a barcode is sent if those get reset as well. If they do, then you only need one `reset()` call.

**Pull request merged**
